package com.moexdelta.moexselect.enums;

public enum ReasonCode {
    HIGH_LIQUIDITY,
    MATCHES_RISK_PROFILE,
    MATCHES_HORIZON,
    GOOD_CREDIT_QUALITY,
    ATTRACTIVE_YIELD,
    SHORT_TERM_LIQUIDITY_MATCH,
    CAPITAL_PRESERVATION_MATCH,
    STABLE_INCOME_MATCH,
    GROWTH_SCENARIO_MATCH,
    COMPLEX_INSTRUMENT,
    LOW_DATA_CONFIDENCE
}
